name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.76.0
        target: x86_64-pc-windows-msvc
        components: rustfmt, clippy
        cache-workspaces: steamworks
    
    - name: Set RUSTFLAGS to allow unexpected cfgs
      shell: bash
      run: echo "RUSTFLAGS=--allow=unexpected_cfgs" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build steamworks dependency
      working-directory: steamworks
      run: |
        npm ci
        npm run build
    
    - name: Install Inno Setup
      run: |
        choco install innosetup -y
    
    - name: Build application and installer
      shell: bash
      run: ./bin/release_win.sh
    
    - name: Create compressed zip of executable
      shell: powershell
      run: |
        Compress-Archive -Path "dist\win\bustle.exe" -DestinationPath "dist\win\bustle.zip" -CompressionLevel Optimal -Force
    
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: bustle-windows
        path: dist/win/bustle.exe
        retention-days: 7
        compression-level: 0
        
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: bustle-installer
        path: dist/win/BustleInstaller.exe
        retention-days: 7
        compression-level: 0
        
    - name: Upload compressed executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: bustle-windows-zip
        path: dist/win/bustle.zip
        retention-days: 7
        compression-level: 0