name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.76.0
        target: x86_64-pc-windows-msvc
        components: rustfmt, clippy
    
    - name: Set RUSTFLAGS to allow unexpected cfgs
      shell: bash
      run: echo "RUSTFLAGS=--allow=unexpected_cfgs" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install pkg globally
      run: npm install -g pkg@5.8.1
    
    - name: Build steamworks dependency
      working-directory: steamworks
      run: |
        npm ci
        npm run build
    
    - name: Build application
      shell: bash
      run: |
        npx tsup
        mkdir -p dist/steamworks
        cp -r steamworks/dist/* dist/steamworks/
        sed -i 's|./dist/win64/|./steamworks/win64/|g' ./dist/index.js
        sed -i 's|const electron = require("electron");||g' ./dist/index.js
        mkdir -p dist/win
        export PKG_CACHE_PATH=".pkg"
        pkg ./dist/index.js -c pkg.json --targets node18-win-x64 --output ./dist/win/bustle.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bustle-windows
        path: dist/win/bustle.exe
        retention-days: 7
        compression-level: 0