name: Create Release

on:
  workflow_run:
    workflows: ["Build Windows Executable"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            })
            
            // Download executable
            const execArtifact = artifacts.data.artifacts.find(artifact => artifact.name === "bustle-windows")
            if (execArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: execArtifact.id,
                archive_format: 'zip'
              })
              const fs = require('fs')
              fs.writeFileSync('bustle-windows.zip', Buffer.from(download.data))
            } else {
              core.warning('No executable artifact found')
            }
            
            // Download installer
            const installerArtifact = artifacts.data.artifacts.find(artifact => artifact.name === "bustle-installer")
            if (installerArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: installerArtifact.id,
                archive_format: 'zip'
              })
              const fs = require('fs')
              fs.writeFileSync('bustle-installer.zip', Buffer.from(download.data))
            } else {
              core.warning('No installer artifact found')
            }
      
      - name: Extract artifacts
        run: |
          mkdir -p artifacts
          unzip -o bustle-windows.zip -d artifacts/ || echo "Failed to extract executable"
          unzip -o bustle-installer.zip -d artifacts/ || echo "Failed to extract installer"
      
      - name: Get version info
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "version=pre-release-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.is_tag == 'true' && format('Release {0}', steps.version.outputs.version) || 'Development Build' }}
          draft: false
          prerelease: ${{ steps.version.outputs.is_tag != 'true' }}
          generate_release_notes: true
          files: |
            artifacts/bustle.exe
            artifacts/BustleInstaller.exe
